### ISSUE TITLE
Add language multiple select a user-nek

### ISSUE THREAD

**Issue by Rettend** [14A-A-Lyedlik-Devs/Gump#289]
```[tasklist]
### Tasks
- [x] Modify userStore (persistent)
- [x] Add *multiple* selection input to header
- [x] Create UI to the left navbar keys to reflect completion (progressbar to support more languages)
```
