### ISSUE TITLE
Improvements to Localer

### ISSUE THREAD

**Issue by Rettend** [14A-A-Lyedlik-Devs/Gump#377]
```[tasklist]
### Tasks
- [x] Refactor the **Next key** button to two ✨ chevrons ✨ - previous and next
- [x] Add a v-if button to quickly jump to an external key if the input references one with `@:AnotherKey`
- [x] Also light up all three **error lights** if all `getContent` requests to GitHub in `fetchTranslations` are successful
- [x] Indicated dirty keys in navbar
- [ ] https://github.com/14A-A-Lyedlik-Devs/Gump/issues/387
- [ ] https://github.com/14A-A-Lyedlik-Devs/Gump/issues/391
- [x] i18n nem szereti a @-t
- [x] 📄 add notes 📄
```
