### ISSUE TITLE
Nuxt Frontend restart

### ISSUE THREAD

**Issue by Rettend** [14A-A-Lyedlik-Devs/Gump#383]
```[tasklist]
### Tasks
- [x] nuxt start
- [x] devtools
- [x] eslint
- [x] i18n module
- [x] unocss: https://unocss.dev/interactive/
- [x] icons: https://icones.netlify.app/collection/fa6-solid
- [x] capacitor: https://ionic.nuxtjs.org/getting-started/#run-on-ios-or-android
- [x] nuxt folder structure: https://nuxt.com/docs/guide/directory-structure/nuxt
- [x] pinia
- [x] vitest
```
