### ISSUE TITLE
Moderation tab

### ISSUE THREAD

**Issue by MAttila42** [14A-A-Lyedlik-Devs/Gump#433]
```[tasklist]
### Tasks
- [x] Bal oldalt egy navbar, a lent felsorolt nézetekkel
- [ ] Egy kis bevezető szöveg a moderátoroknak
```

```[tasklist]
### Nézetek
- [ ] https://github.com/14A-A-Lyedlik-Devs/Gump/issues/465
- [ ] https://github.com/14A-A-Lyedlik-Devs/Gump/issues/466
- [ ] https://github.com/14A-A-Lyedlik-Devs/Gump/issues/468
- [ ] https://github.com/14A-A-Lyedlik-Devs/Gump/issues/469
```
