### ISSUE TITLE
Adverts Moderation View

### ISSUE THREAD

**Issue by MAttila42** [14A-A-Lyedlik-Devs/Gump#469]
```[tasklist]
### Tasks
- [x] Összes reklám lista
- [x] Szűrés partner id-re
- [x] Új reklám felvétele
- [x] Reklám módosítása
- [x] Reklám törlése
```
